load("@rules_license//rules:license.bzl", "license")
load("@rules_license//rules:license_kind.bzl", "license_kind")

package(
    default_applicable_licenses = [":license"],
    default_visibility = ["//visibility:public"],
)

license(
    name = "license",
    license_kinds = [
        ":SPDX-license-identifier-BSD-3-Clause",
    ],
    license_text = "COPYING",
    visibility = [":__subpackages__"],
)

license_kind(
    name = "SPDX-license-identifier-BSD-3-Clause",
    conditions = ["notice"],
    url = "https://spdx.org/licenses/BSD-3-Clause.html",
)

cc_library(
    name = "rnn_vad",
    srcs = [
        "src/rnn_activations.h",
        "src/rnn_vad_weights.cc",
        "src/rnn_vad_weights.h",
    ],
    hdrs = [
        "src/rnn_activations.h",
        "src/rnn_vad_weights.h",
    ],
)
